// Generated by gencpp from file main_loop/AddTwoInts.msg
// DO NOT EDIT!


#ifndef MAIN_LOOP_MESSAGE_ADDTWOINTS_H
#define MAIN_LOOP_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <main_loop/AddTwoIntsRequest.h>
#include <main_loop/AddTwoIntsResponse.h>


namespace main_loop
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace main_loop


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::main_loop::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::main_loop::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::main_loop::AddTwoInts > {
  static const char* value()
  {
    return "main_loop/AddTwoInts";
  }

  static const char* value(const ::main_loop::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::main_loop::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::main_loop::AddTwoInts > 
template<>
struct MD5Sum< ::main_loop::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::main_loop::AddTwoInts >::value();
  }
  static const char* value(const ::main_loop::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::main_loop::AddTwoIntsRequest> should match 
// service_traits::DataType< ::main_loop::AddTwoInts > 
template<>
struct DataType< ::main_loop::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::main_loop::AddTwoInts >::value();
  }
  static const char* value(const ::main_loop::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::main_loop::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::main_loop::AddTwoInts > 
template<>
struct MD5Sum< ::main_loop::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::main_loop::AddTwoInts >::value();
  }
  static const char* value(const ::main_loop::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::main_loop::AddTwoIntsResponse> should match 
// service_traits::DataType< ::main_loop::AddTwoInts > 
template<>
struct DataType< ::main_loop::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::main_loop::AddTwoInts >::value();
  }
  static const char* value(const ::main_loop::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAIN_LOOP_MESSAGE_ADDTWOINTS_H
