// Generated by gencpp from file main_loop/goap_Request.msg
// DO NOT EDIT!


#ifndef MAIN_LOOP_MESSAGE_GOAP_REQUEST_H
#define MAIN_LOOP_MESSAGE_GOAP_REQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace main_loop
{
template <class ContainerAllocator>
struct goap_Request_
{
  typedef goap_Request_<ContainerAllocator> Type;

  goap_Request_()
    : action_done(false)
    , pos()
    , north_or_south(0)
    , time(0.0)
    , mission_name()
    , mission_child_name()  {
    }
  goap_Request_(const ContainerAllocator& _alloc)
    : action_done(false)
    , pos(_alloc)
    , north_or_south(0)
    , time(0.0)
    , mission_name(_alloc)
    , mission_child_name(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _action_done_type;
  _action_done_type action_done;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _pos_type;
  _pos_type pos;

   typedef int32_t _north_or_south_type;
  _north_or_south_type north_or_south;

   typedef float _time_type;
  _time_type time;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mission_name_type;
  _mission_name_type mission_name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mission_child_name_type;
  _mission_child_name_type mission_child_name;





  typedef boost::shared_ptr< ::main_loop::goap_Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::main_loop::goap_Request_<ContainerAllocator> const> ConstPtr;

}; // struct goap_Request_

typedef ::main_loop::goap_Request_<std::allocator<void> > goap_Request;

typedef boost::shared_ptr< ::main_loop::goap_Request > goap_RequestPtr;
typedef boost::shared_ptr< ::main_loop::goap_Request const> goap_RequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::main_loop::goap_Request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::main_loop::goap_Request_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace main_loop

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'main_loop': ['/home/frank/catkin_ws/src/main_loop/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::main_loop::goap_Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::main_loop::goap_Request_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::main_loop::goap_Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::main_loop::goap_Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::main_loop::goap_Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::main_loop::goap_Request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::main_loop::goap_Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "24e4b27fcff005a29854ec9235284e64";
  }

  static const char* value(const ::main_loop::goap_Request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x24e4b27fcff005a2ULL;
  static const uint64_t static_value2 = 0x9854ec9235284e64ULL;
};

template<class ContainerAllocator>
struct DataType< ::main_loop::goap_Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "main_loop/goap_Request";
  }

  static const char* value(const ::main_loop::goap_Request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::main_loop::goap_Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool action_done\n"
"int32[] pos\n"
"\n"
"int32 north_or_south\n"
"\n"
"float32 time\n"
"string mission_name\n"
"string mission_child_name\n"
;
  }

  static const char* value(const ::main_loop::goap_Request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::main_loop::goap_Request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_done);
      stream.next(m.pos);
      stream.next(m.north_or_south);
      stream.next(m.time);
      stream.next(m.mission_name);
      stream.next(m.mission_child_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct goap_Request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::main_loop::goap_Request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::main_loop::goap_Request_<ContainerAllocator>& v)
  {
    s << indent << "action_done: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.action_done);
    s << indent << "pos[]" << std::endl;
    for (size_t i = 0; i < v.pos.size(); ++i)
    {
      s << indent << "  pos[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.pos[i]);
    }
    s << indent << "north_or_south: ";
    Printer<int32_t>::stream(s, indent + "  ", v.north_or_south);
    s << indent << "time: ";
    Printer<float>::stream(s, indent + "  ", v.time);
    s << indent << "mission_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mission_name);
    s << indent << "mission_child_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mission_child_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAIN_LOOP_MESSAGE_GOAP_REQUEST_H
