// Generated by gencpp from file main_loop/goap_.msg
// DO NOT EDIT!


#ifndef MAIN_LOOP_MESSAGE_GOAP__H
#define MAIN_LOOP_MESSAGE_GOAP__H

#include <ros/service_traits.h>


#include <main_loop/goap_Request.h>
#include <main_loop/goap_Response.h>


namespace main_loop
{

struct goap_
{

typedef goap_Request Request;
typedef goap_Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct goap_
} // namespace main_loop


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::main_loop::goap_ > {
  static const char* value()
  {
    return "bea0114d84bf82ce48ef39139983607f";
  }

  static const char* value(const ::main_loop::goap_&) { return value(); }
};

template<>
struct DataType< ::main_loop::goap_ > {
  static const char* value()
  {
    return "main_loop/goap_";
  }

  static const char* value(const ::main_loop::goap_&) { return value(); }
};


// service_traits::MD5Sum< ::main_loop::goap_Request> should match 
// service_traits::MD5Sum< ::main_loop::goap_ > 
template<>
struct MD5Sum< ::main_loop::goap_Request>
{
  static const char* value()
  {
    return MD5Sum< ::main_loop::goap_ >::value();
  }
  static const char* value(const ::main_loop::goap_Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::main_loop::goap_Request> should match 
// service_traits::DataType< ::main_loop::goap_ > 
template<>
struct DataType< ::main_loop::goap_Request>
{
  static const char* value()
  {
    return DataType< ::main_loop::goap_ >::value();
  }
  static const char* value(const ::main_loop::goap_Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::main_loop::goap_Response> should match 
// service_traits::MD5Sum< ::main_loop::goap_ > 
template<>
struct MD5Sum< ::main_loop::goap_Response>
{
  static const char* value()
  {
    return MD5Sum< ::main_loop::goap_ >::value();
  }
  static const char* value(const ::main_loop::goap_Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::main_loop::goap_Response> should match 
// service_traits::DataType< ::main_loop::goap_ > 
template<>
struct DataType< ::main_loop::goap_Response>
{
  static const char* value()
  {
    return DataType< ::main_loop::goap_ >::value();
  }
  static const char* value(const ::main_loop::goap_Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAIN_LOOP_MESSAGE_GOAP__H
