// Generated by gencpp from file main_loop/path.msg
// DO NOT EDIT!


#ifndef MAIN_LOOP_MESSAGE_PATH_H
#define MAIN_LOOP_MESSAGE_PATH_H

#include <ros/service_traits.h>


#include <main_loop/pathRequest.h>
#include <main_loop/pathResponse.h>


namespace main_loop
{

struct path
{

typedef pathRequest Request;
typedef pathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct path
} // namespace main_loop


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::main_loop::path > {
  static const char* value()
  {
    return "aa24ea267d1480041af4f206230a297f";
  }

  static const char* value(const ::main_loop::path&) { return value(); }
};

template<>
struct DataType< ::main_loop::path > {
  static const char* value()
  {
    return "main_loop/path";
  }

  static const char* value(const ::main_loop::path&) { return value(); }
};


// service_traits::MD5Sum< ::main_loop::pathRequest> should match 
// service_traits::MD5Sum< ::main_loop::path > 
template<>
struct MD5Sum< ::main_loop::pathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::main_loop::path >::value();
  }
  static const char* value(const ::main_loop::pathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::main_loop::pathRequest> should match 
// service_traits::DataType< ::main_loop::path > 
template<>
struct DataType< ::main_loop::pathRequest>
{
  static const char* value()
  {
    return DataType< ::main_loop::path >::value();
  }
  static const char* value(const ::main_loop::pathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::main_loop::pathResponse> should match 
// service_traits::MD5Sum< ::main_loop::path > 
template<>
struct MD5Sum< ::main_loop::pathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::main_loop::path >::value();
  }
  static const char* value(const ::main_loop::pathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::main_loop::pathResponse> should match 
// service_traits::DataType< ::main_loop::path > 
template<>
struct DataType< ::main_loop::pathResponse>
{
  static const char* value()
  {
    return DataType< ::main_loop::path >::value();
  }
  static const char* value(const ::main_loop::pathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAIN_LOOP_MESSAGE_PATH_H
