// Generated by gencpp from file main_loop/pathResponse.msg
// DO NOT EDIT!


#ifndef MAIN_LOOP_MESSAGE_PATHRESPONSE_H
#define MAIN_LOOP_MESSAGE_PATHRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace main_loop
{
template <class ContainerAllocator>
struct pathResponse_
{
  typedef pathResponse_<ContainerAllocator> Type;

  pathResponse_()
    : next_pos_x(0)
    , next_pos_y(0)
    , degree(0.0)
    , blocked(false)  {
    }
  pathResponse_(const ContainerAllocator& _alloc)
    : next_pos_x(0)
    , next_pos_y(0)
    , degree(0.0)
    , blocked(false)  {
  (void)_alloc;
    }



   typedef int32_t _next_pos_x_type;
  _next_pos_x_type next_pos_x;

   typedef int32_t _next_pos_y_type;
  _next_pos_y_type next_pos_y;

   typedef float _degree_type;
  _degree_type degree;

   typedef uint8_t _blocked_type;
  _blocked_type blocked;





  typedef boost::shared_ptr< ::main_loop::pathResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::main_loop::pathResponse_<ContainerAllocator> const> ConstPtr;

}; // struct pathResponse_

typedef ::main_loop::pathResponse_<std::allocator<void> > pathResponse;

typedef boost::shared_ptr< ::main_loop::pathResponse > pathResponsePtr;
typedef boost::shared_ptr< ::main_loop::pathResponse const> pathResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::main_loop::pathResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::main_loop::pathResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace main_loop

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'main_loop': ['/home/frank/catkin_ws/src/main_loop/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::main_loop::pathResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::main_loop::pathResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::main_loop::pathResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::main_loop::pathResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::main_loop::pathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::main_loop::pathResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::main_loop::pathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3ca94551c32873de91ff62acdf329f56";
  }

  static const char* value(const ::main_loop::pathResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3ca94551c32873deULL;
  static const uint64_t static_value2 = 0x91ff62acdf329f56ULL;
};

template<class ContainerAllocator>
struct DataType< ::main_loop::pathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "main_loop/pathResponse";
  }

  static const char* value(const ::main_loop::pathResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::main_loop::pathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 next_pos_x\n"
"int32 next_pos_y\n"
"float32 degree\n"
"bool blocked\n"
"\n"
"\n"
;
  }

  static const char* value(const ::main_loop::pathResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::main_loop::pathResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.next_pos_x);
      stream.next(m.next_pos_y);
      stream.next(m.degree);
      stream.next(m.blocked);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pathResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::main_loop::pathResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::main_loop::pathResponse_<ContainerAllocator>& v)
  {
    s << indent << "next_pos_x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.next_pos_x);
    s << indent << "next_pos_y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.next_pos_y);
    s << indent << "degree: ";
    Printer<float>::stream(s, indent + "  ", v.degree);
    s << indent << "blocked: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.blocked);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAIN_LOOP_MESSAGE_PATHRESPONSE_H
