// Generated by gencpp from file lidar_2020/alert_range.msg
// DO NOT EDIT!


#ifndef LIDAR_2020_MESSAGE_ALERT_RANGE_H
#define LIDAR_2020_MESSAGE_ALERT_RANGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace lidar_2020
{
template <class ContainerAllocator>
struct alert_range_
{
  typedef alert_range_<ContainerAllocator> Type;

  alert_range_()
    : header()
    , num(0)
    , ranging_value()
    , alert()  {
    }
  alert_range_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , num(0)
    , ranging_value(_alloc)
    , alert(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _num_type;
  _num_type num;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _ranging_value_type;
  _ranging_value_type ranging_value;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _alert_type;
  _alert_type alert;





  typedef boost::shared_ptr< ::lidar_2020::alert_range_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lidar_2020::alert_range_<ContainerAllocator> const> ConstPtr;

}; // struct alert_range_

typedef ::lidar_2020::alert_range_<std::allocator<void> > alert_range;

typedef boost::shared_ptr< ::lidar_2020::alert_range > alert_rangePtr;
typedef boost::shared_ptr< ::lidar_2020::alert_range const> alert_rangeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lidar_2020::alert_range_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lidar_2020::alert_range_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lidar_2020

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'lidar_2020': ['/home/frank/catkin_ws/src/lidar_2020/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lidar_2020::alert_range_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidar_2020::alert_range_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_2020::alert_range_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_2020::alert_range_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_2020::alert_range_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_2020::alert_range_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lidar_2020::alert_range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d0c52c82e08087063181441d7bcd4d6e";
  }

  static const char* value(const ::lidar_2020::alert_range_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd0c52c82e0808706ULL;
  static const uint64_t static_value2 = 0x3181441d7bcd4d6eULL;
};

template<class ContainerAllocator>
struct DataType< ::lidar_2020::alert_range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lidar_2020/alert_range";
  }

  static const char* value(const ::lidar_2020::alert_range_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lidar_2020::alert_range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"int16 num\n"
"float32[] ranging_value\n"
"bool[] alert\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::lidar_2020::alert_range_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lidar_2020::alert_range_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.num);
      stream.next(m.ranging_value);
      stream.next(m.alert);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct alert_range_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lidar_2020::alert_range_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lidar_2020::alert_range_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "num: ";
    Printer<int16_t>::stream(s, indent + "  ", v.num);
    s << indent << "ranging_value[]" << std::endl;
    for (size_t i = 0; i < v.ranging_value.size(); ++i)
    {
      s << indent << "  ranging_value[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.ranging_value[i]);
    }
    s << indent << "alert[]" << std::endl;
    for (size_t i = 0; i < v.alert.size(); ++i)
    {
      s << indent << "  alert[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.alert[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIDAR_2020_MESSAGE_ALERT_RANGE_H
