(cl:in-package main_loop-srv)
(cl:export '(ACTION_DONE-VAL
          ACTION_DONE
          POS-VAL
          POS
          NORTH_OR_SOUTH-VAL
          NORTH_OR_SOUTH
          TIME-VAL
          TIME
          MISSION_NAME-VAL
          MISSION_NAME
          MISSION_CHILD_NAME-VAL
          MISSION_CHILD_NAME
          SPEED-VAL
          SPEED
          MODE-VAL
          MODE
          DEGREE-VAL
          DEGREE
          POS-VAL
          POS
          ST2-VAL
          ST2
          IS_WAIT-VAL
          IS_WAIT
          MISSION_NAME-VAL
          MISSION_NAME
          MISSION_CHILD_NAME-VAL
          MISSION_CHILD_NAME
))