(cl:in-package main_loop-srv)
(cl:export '(MY_POS_X-VAL
          MY_POS_X
          MY_POS_Y-VAL
          MY_POS_Y
          ENEMY1_X-VAL
          ENEMY1_X
          ENEMY1_Y-VAL
          ENEMY1_Y
          ENEMY2_X-VAL
          ENEMY2_X
          ENEMY2_Y-VAL
          ENEMY2_Y
          ALLY_X-VAL
          ALLY_X
          ALLY_Y-VAL
          ALLY_Y
          GOAL_POS_X-VAL
          GOAL_POS_X
          GOAL_POS_Y-VAL
          GOAL_POS_Y
          NEXT_POS_X-VAL
          NEXT_POS_X
          NEXT_POS_Y-VAL
          NEXT_POS_Y
          DEGREE-VAL
          DEGREE
          BLOCKED-VAL
          BLOCKED
))