(cl:in-package main_loop-msg)
(cl:export '(HEADER-VAL
          HEADER
          EMERGENCY-VAL
          EMERGENCY
          MY_POS_X-VAL
          MY_POS_X
          MY_POS_Y-VAL
          MY_POS_Y
          MY_DEGREE-VAL
          MY_DEGREE
          ENEMY1_X-VAL
          ENEMY1_X
          ENEMY1_Y-VAL
          ENEMY1_Y
          ENEMY2_X-VAL
          ENEMY2_X
          ENEMY2_Y-VAL
          ENEMY2_Y
          ALLY_X-VAL
          ALLY_X
          ALLY_Y-VAL
          ALLY_Y
          SERVO_STATE-VAL
          SERVO_STATE
          STEPPER-VAL
          STEPPER
          HAND-VAL
          HAND
          STATUS-VAL
          STATUS
          TIME-VAL
          TIME
))